spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.4-nano
          max-completion-tokens: 200
    vectorstore:
      pgvector:
        initialize-schema: true

  jwt:
    issuer: spig-api
    secret: ${JWT_SECRET}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

file:
  upload:
    directory: ${FILE_UPLOAD_DIR:./uploads/learning}